apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: where-for-dinner-ui
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=where-for-dinner-ui"
  links:
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/
      icon: docs
      title: Customer-facing Docs
    - url: https://github.com/pivotal/docs-tap
      icon: github
      title: Docs Source Code
    - url: https://network.tanzu.vmware.com/products/tanzu-application-platform/
      icon: catalog
      title: Tanzu Network Product Page
spec:
  type: service
  lifecycle: experimental
  owner: where-for-dinner-team
  system: where-for-dinner
  dependsOn: 
    - component:where-for-dinner-search
    - component:where-for-dinner-availability
